version: '3'

services:
  mysql:
    image: mysql:8.0.28
    container_name: mysql
    environment:
      MYSQL_DATABASE: testdb
    volumes:
      - C:\Users\user\Desktop\docker-test:/var/lib/mysql
    networks:
      - app_network

  backend:
    image: makouz/tuto_backend:1.0.0
    container_name: backend_container
    ports:
      - "8080:2222"
    networks:
      - app_network
    depends_on:
      - mysql

  frontend:
    image: makouz/tuto_front:1.0.0
    container_name: frontend_container
    ports:
      - "8088:80"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
