version: '3.8'
services:
  mysql:
    image: mysql:8.0.28
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=testdb
    networks:
      - exercice2_network
    ports:
      - "3306:3306"
    volumes:
      - exercice2_volume:/var/lib/mysql
  backend:
    image: makouz/tuto_backend:1.0.0
    container_name: backend
    ports:
      - "8080:2222"
    networks:
      - exercice2_network
    depends_on:
      - mysql
  frontend:
    image: makouz/tuto_front:1.0.0
    container_name: frontend
    ports:
      - "80:8088"
    networks:
      - exercice2_network
    depends_on:
      - backend

networks:
  exercice2_network:
    driver: Bridge

volumes:
  exercice2_volume: 
